css:
  product:
    fileName: product.css
    media: all
    priority: 200
    include:
      - product
  checkout:
    fileName: checkout.css
    media: all
    priority: 200
    include:
      - cart
      - checkout
      - order-confirmation
  listing:
    fileName: listing.css
    media: all
    priority: 200
    include:
      - category
      - prices-drop
      - new-products
      - best-sales
      - manufacturer
      - search
      - module-is_favoriteproducts-favorite

js:
  runtime: # This file is only used to handle HMR for multiple entry points
    fileName: runtime.js
    priority: 1
  swipervendor:
    fileName: swipervendor.js
    priority: 1
  product:
    fileName: product.js
    priority: 200
    include:
      - product
  checkout:
    fileName: checkout.js
    priority: 200
    include:
      - cart
      - checkout
      - order-confirmation
  listing:
    fileName: listing.js
    priority: 200
    include:
      - category
      - prices-drop
      - new-products
      - best-sales
      - manufacturer
      - search
      - module-is_favoriteproducts-favorite
